//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string role { get; set; }
        public string MailID { get; set; }
        public string City { get; set; }
    }
}
